services:
  - type: web
    name: property-manager-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn property_manager_backend.wsgi:application
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: property-manager-db
          property: connectionString
